Added a simple slots game command.
thatjar/1bot pull request #1
Opened 2021-10-04 07:37 UTC by ChaoticNebula5

2021-10-04 07:40 UTC, Tommins-IT reviewed
It could be improved but it's good. Also, for the color, you have to use the hex code of 1Bot's embeds.

2021-10-04 07:44 UTC, opensourze commented
It's good... but as @Tommins-IT said, can you improve it a bit? You can say that you won if there's 3 sevens.

2021-10-04 08:11 UTC, opensourze commented on cogs/fun.py
> +        embed.set_footer(text="You need triple 7's to win.")
You could add an `if` statement that checks if `embed.description` is three sevens and set the footer accordingly

2021-10-04 08:13 UTC, opensourze requested changes
I've left a comment, also the embed colour for 1Bot is `0xFF6600` (although it's not that important)

2021-10-04 12:44 UTC, merged

2021-10-05 05:10 UTC, ChaoticNebula5 commented
Alright, I'll try! Sorry for the late response, my internet died for a day.

2021-10-05 05:16 UTC, opensourze commented
Oh it's fine, I already merged it :P

2021-10-05 06:07 UTC, ChaoticNebula5 commented
Oops just saw it xD